version: '3'

services:
    php:
        build:
            context: ./docker/php
        volumes:
            - ./app:/opt/app
            - ./docker/php/zz-log.conf:/usr/local/etc/php-fpm.d/zz-log.conf
    web:
        image: nginx:latest
        depends_on:
          - php
        ports:
            - "8080:80"
        volumes:
            - ./app:/opt/app
            - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
